trigger:
  branches:
    include:
      - main

pool: Shivg19

stages:
  - stage: Terraform
    displayName: "Terraform Stage"

    jobs:
      - job: TerraformJob
        displayName: "Terraform Init Plan Apply"

        steps:
          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: "latest"

          - task: TerraformTask@5
            displayName: "Terraform Init"
            inputs:
              provider: "azurerm"
              command: "init"
              backendServiceArm: "Service Connection Shiv"
              backendAzureRmStorageAccountName: "ramesh1212"
              backendAzureRmContainerName: "rakesh1213"
              backendAzureRmKey: "rd.tfstate"

          - task: TerraformTask@5
            displayName: "Terraform Apply"
            inputs:
              provider: "azurerm"
              command: "apply"
              environmentServiceNameAzureRM: "Service Connection Shiv"