trigger:
 branches:
    include:
     - main

pool: lokeshg8

stages:
  - stage: 
    jobs:
      - job: 
        steps:
          - 
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'infrapipeline01'
    backendAzureRmStorageAccountName: 'infrapipeline02'
    backendAzureRmContainerName: 'infracontainer03'
    backendAzureRmKey: 'terraform.tfstate'