trigger:
  branches:
    include:
      - main

pool:
  name: lokeshg8

stages:
- stage: Terraform_Init
  displayName: "Terraform Init Stage"

  jobs:
  - job: TerraformInit
    displayName: "Terraform Initialization"

    steps:

    - task: TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'infrapipeline01'
        backendAzureRmStorageAccountName: 'infrapipeline02'
        backendAzureRmContainerName: 'infracontainer03'
        backendAzureRmKey: 'terraform.tfstate'